[package]
name = "pets_lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
concat-idents = "1.1.5"
godot = { git = "https://github.com/godot-rust/gdext", branch = "master" }
num-derive = "0.4.0"
num-traits = "0.2.16"
serde = {version = "1.0.188", features= ["derive", "rc"] }
serde_json = "1.0.107"
